language: erlang
matrix:
  include:
    - os: linux
      otp_release: 20.0
script:
  - "rebar3 do xref, ct, dialyzer"
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.cache/rebar3/hex/default"
